POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "käyttäjä toine bloggi",
    "author": "kirjoittaja",
    "url": "https://google.fi/",
    "likes": 1234,
    "userId": "5f0594ed84057a52bbfffec0"
}